export const ADD_TO_WISH_LIST = "ADD_TO_WISH_LIST";
export const REMOVE_FROM_WISH_LIST = "REMOVE_FROM_WISH_LIST";

export const CHANGE_SEARCH_VALUE = "CHANGE_SEARCH_VALUE";

export const INITIALIZE_PRODUCTS = "INITIALIZE_PRODUCTS";
export const FILTER_PRODUCTS = "FILTER_PRODUCTS";
export const REFRESH_PRODUCTS = "REFRESH_PRODUCTS";
